config/routes.rb
Shaders::Application.routes.draw do
  root :to => 'home#index'

  resources :color_schemes
  resource :editor
end

app/models/color_scheme.rb
class ColorScheme < ActiveRecord::Base
  attr_accessible :name
  has_many :color_scheme_data, order: 'position'
end

app/models/color_scheme_datum.rb
class ColorSchemeDatum < ActiveRecord::Base
  attr_accessible :color, :time, :position

  belongs_to :color_scheme
  acts_as_list :scope => :color_scheme
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/color_schemes_controller.rb
class ColorSchemesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    color_scheme = ColorScheme.create(name: params[:name])

    params[:color_scheme_data].to_a.sort {|x, y| x[0].to_i <=> y[0].to_i}.each do |datum|
      color_scheme.color_scheme_data.create(color: datum["color"], time: datum["time"].to_f)
    end
  end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/color_schemes_helper.rb
module ColorSchemesHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/color_schemes/index.haml
- ColorScheme.all.each do |color_scheme|
  .color_scheme
    = link_to color_scheme.name, color_scheme_path(color_scheme)

app/views/color_schemes/new.haml
.color_schemer
  .canvases
    .canvas_box
      .inner
        %canvas.gradient
    .canvas_box
      .inner
        %canvas.gray
    .canvas_box
      .inner
        %canvas.transformed
      .animate_box
        .text
          Animate:
        %input{type: 'checkbox', class: 'animate'}

  %br{clear: 'both'}

  .instructions
    .explanation
      .part_1
        This tool takes a list of pairs of [color, value] and converts it into a valid glsl function whose input is a value between 0.0 and 1.0 and a color (represented as a vec3).
      .part_2
        The function interpolates the colors. For instance, the exmple to the right sends 0.0 to white (#ffffff) and 1.0 to black (#000000).
      .part_3
        The webcam shaders (above - grayscale & colored) are provided to show what happens when an image is sent through your function (black -> 0.0, white -> 1.0).
    .instruction_title
      Instructions:
    .instruction
      1. Hit "Allow" three times to allow all of the shaders access to the camera.
    .instruction
      2. Fill in colors and the values where you wish the function to attain those colors.
    .instruction
      3. Hit "Add Picker" to add another set of values.
    .instruction.optional
      Optional: Hit "Import Random" to import a random color palette from
      = link_to 'colourlovers.com', 'http://colourlovers.com'
    .instruction.optional
      Optional: Click "Animate" under the shader on ther right to make the colors change cyclically.
    .instruction.optional
      Optional: Click a shader to make it full-screen. Click again to leave full-screen mode.

  .pickers{clear: 'both'}
    .basic_functions
      = link_to 'Add Picker', '#', class: 'add_picker'
      = link_to 'Remove Picker', '#', class: 'remove_picker'
    .advanced_functions
      = link_to 'Import Random', '#', class: 'import_random'
      = link_to 'Save', '#', class: 'save'

    .name
      Name:
      %input{type: 'text', class: 'function_name', value: 'function_name'}

    .picker
      %div.first_color
        .heading
          Color
        .input
          %input{type: 'text', class: 'color', value: '#ffffff'}
      %div.first_time
        .heading
          Value
        .input
          %input{type: 'text', class: 'time', value: '0.0'}
    .picker
      %div
        %input{type: 'text', class: 'color', value: '#000000'}
      %div
        %input{type: 'text', class: 'time', value: '1.0'}

  .output{clear: 'both'}
    .title
      CODE:
    %textarea.code

app/views/editors/show.haml
%canvas#canvas

#editor

app/views/home/index.haml
.content
  = link_to 'Color Schemes', color_schemes_path
  = link_to 'Editor', editor_path

app/views/layouts/application.haml
%html
  %head
    %title Shaders
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  = yield